name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    name: Build, Publish, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache Node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Node modules
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build pdf-worker
        run: npm run build
        # Currently necessary for Webpack: https://stackoverflow.com/a/69746937
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Upload pre-build ZIP
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          npm publish --@charliej107:registry=https://npm.pkg.github.com

      - name: Run tests
        run: npm run test
